name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]  # branch to trigger deployment

permissions:  # Explicitly setting permissions
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04  # Specifies the runner environment
    environment:
      name: github-pages  # This is the required environment name for GitHub Pages deployments
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you need for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Sphinx Documentation
        run: |
          chmod +x docs/rebuild-docs.sh
          ./docs/rebuild-docs.sh  # Runs your script to build the documentation

      - name: Prepare CNAME
        run: echo 'www.perfsim.com' > docs/_build/html/CNAME  # Creates a CNAME file in the publish directory
      
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
